### ISSUE TITLE
Start Accumulating Migration IATI Dataset

### ISSUE THREAD

**Issue by Brentophillips** [BeehiveNGO/AnalysisLab#5]
Start accumulating IATI data from countries impacted by the migration of Syrian refugees beginning with Greece, Albania, Macedonia, Bulgaria and Italy

**Comment by janetpak** [comment]
Can you explain how the migration data will look?

**Comment by Brentophillips** [comment]
I've added some Getting Started [Collecting IATI Data](https://github.com/BeehiveNGO/AnalysisLab/blob/master/files/Collecting_IATI_Data.md) instructions into the Analysis repo

**Comment by Brentophillips** [comment]
Our main priority right now is to collect XML files published by different organizations and file these into country folders. Then we're going to work on combining them together. Here is an example of a [CSV file]() covering Albania. Our file will contain more headings, see issue #3

**Comment by janetpak** [comment]
The CSV file doesn't open.
